baseURL = "https://critstrike.github.io/"
languageCode = "en-us"
title = "Critstrike"

# Set Theme
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
  # LoveIt set to dark theme
  defaultTheme = "dark"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is allowed), such as icons
    pre = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Home Page Info
[params.home]
  [params.home.profile]
    enable = true
    typeit = false
    social = true

# Social information
[params.social]
  GitHub = "critstrike"
